# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-Wachovia
version:      0.4
version_from: lib/Finance/Bank/Wachovia.pm
installdirs:  site
requires:
    Crypt::CBC:                    0
    Crypt::DES_PP:                 0
    HTTP::Cookies:                 0
    Test::More:                    0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
